bucket/policy/action.go

Needed for existing object replication - https://github.com/minio/minio/pull/12109/files

Add ResetBucketReplicationState action

---

iam/policy/admin-action.go

Required for upcoming feature.
This PR will be linked.

Add admin:DownloadRaw action

---

certs/certs.go

Allows reload on OS signal or manual reloads.
Some simplifications to existing code added.
First part of https://github.com/minio/minio/issues/13662

Add certificate reload functions

---

bucket/policy/policy.go
iam/policy/policy.go

Needed for site replication visibility

Add helper methods to test policy equality

---

wildcard/match.go
wildcard/match_test.go

Fixes https://github.com/minio/minio/issues/14795
Document difference between Match/MatchSimple

Fix simple match crash

---

.github/workflows/go.yml
Makefile
bucket/policy/action.go
iam/policy/action.go

refer https://github.com/minio/minio/issues/10265
This change is needed before we get server side support

allow valid tagging conditionals to various API actions

---

iam/policy/constants.go
iam/policy/policy.go
iam/policy/statement.go

Update console admin policy and allowed kms:* actions to be processed

Update console admin policy and allowed kms:* actions to be processed

---

iam/policy/kms-action.go

Adds extra kms actions in pkg so other KES endpoints can be called from minio and console

Add extra kms actions

---

licverifier/verifier.go

So that it can be included in the output of `mc license info`

Add license id to LicenseInfo struct

---

ldap/validation.go
ldap/validation_test.go

Catches another set of potential user errors early:
- Check that Base DNs parse successfully as DNs
- Check that Base DNs do not represent overlapping subtrees
- Check that LDAP search filters compile

Add additional LDAP config validation

---

iam/policy/statement.go
iam/policy/statement_test.go

I'm trying to fix minio/minio#15328 to implement `NotAction` field in a policy statement.

feat(iam/policy): support NotAction field

---

iam/policy/admin-action.go

add cancel batch job action

---

bucket/policy/condition/boolfunc.go
bucket/policy/condition/datefunc.go
bucket/policy/condition/ipaddrfunc.go
bucket/policy/condition/nullfunc.go
bucket/policy/condition/numericfunc.go
console/console_test.go
iam/policy/statement.go
net/url.go

These utility functions are required for a change in minio/minio (will add the PR reference soon)

Add utility functions to check for specific connection errors

---

event/errors.go
event/event.go
event/name.go

Moves the structs for lambda notification from MinIO to `pkg`

Move Event Structs from minio/internal

---

bucket/policy/action.go
bucket/policy/action_test.go
bucket/policy/actionset.go
bucket/policy/actionset_test.go
bucket/policy/statement.go
iam/policy/action.go
iam/policy/actionset.go

Goal here is to identify the differences in the implementations of the two iam/policy and bucket/policy packages and eventually merge them into a single package without too much code duplication

Catch up action set implementation in policy pkgs

---

sftp/sftp.go

These changes enable us to pass a context into the sftp server for a controlled shutdown. Additionally it enables optional tcp keep-alive configurations.

Adding Context awareness and the ability to control tcp keep-alive

---

policy/actionset.go
policy/condition/keyname.go
policy/statement.go
policy/sts-action.go

with sts:DurationSeconds as well

Add policy support of sts:AssumeRoleWithWebIdentity

---

subnet/license.go

If the license has expired (and grace period also over where applicable), then exit from the program.
To achieve this, the function `ValidateEnterpriseLicense` which is called at application startup will also schedule the next license check after successful validation.
If the license is currently not expired, schedule to check again just after expiry. If it is expired but within grace period, check every day.

Exit if license expired

---

policy/action.go
policy/condition/keyname.go

Add `s3:x-amz-server-side-encryption-aws-kms-key-id` to the allowed HTTP headers list

Additional allowed HTTP header

---

xtime/time_contrib_test.go

test: add w d test case for xtime

test: add w d test case for xtime

---

ldap/ldap.go

This commit replaces the custom root CA pool and the skip-verify flag with a dedicated TLS client config. Now, the client TLS config can be customized.

ldap: replace `RootCAs` and `InsecureSkipVerify` with `tls.Config`

---

ldap/validation_test.go
xtime/time.go
xtime/time_unmarshal_test.go

Adds MarshalYAML function which converts Duration to human readable string, to map with the existing UnMarshalYAML (it expects human readable string)

Marshal xtime.Duration

---

policy/bucket-policy-statement.go
policy/bucket-policy-statement_test.go

Adds NotResource policy element as specified in S3 docs. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notresource.html
From minio/minio#20719

Add NotResource policy element

---

net/url.go

Add `use of closed network connection` and `An existing connection was forcibly closed by the remote host`.

Add more net errors

---

certs/manager.go

This would returns latest loaded certs

Add function `GetAllCertificates`

---

policy/policy.go
policy/policy_bench_test.go

The main benefits include
- Single policy inputs for typical cases; no need to copy the policy.
- actionStatementIndex() should only allocate the map when necessary, 
avoiding it for Deny-only cases and cases with only wildcard actions.
- There is no requirement to clone() statements; we are not planning 
to modify the resources per statement.
```
benchmark                                                old ns/op     new ns/op     delta
BenchmarkMergePolicies/10Policies_1Stmt_NoDups-8         10099         3993          -60.46%
BenchmarkMergePolicies/10Policies_1Stmt_HalfDups-8       9597          3420          -64.36%
BenchmarkMergePolicies/100Policies_1Stmt_NoDups-8        90724         35601         -60.76%
BenchmarkMergePolicies/100Policies_1Stmt_HalfDups-8      93520         30534 …
```

improve further mergePolicies to return faster

---

policy/action.go
policy/admin-action.go
policy/condition/name.go
policy/condition/stringfunc.go
policy/policy.go
policy/policy_bench_test.go

We are working a policy builder in console, for this we need to expose these constants so they can use to populate the different inputs in the UI component
Part of https://github.com/miniohq/aistor-console/issues/4911
Console implementation: https://github.com/miniohq/aistor-console/pull/4912

Expose policy constants for actions, conditions
