- licverifier/verifier.go
- licverifier/verifier_test.go
Trial licenses will have the Account ID as 0.
Added a new test to cover this.
> fix license verifier for trial licenses

- console/console.go
- console/console_test.go
- console/themes.go
To fix the following crash:
```
fatal error: concurrent map read and map write
goroutine 98 [running]:
runtime.throw({0x4b8b456, 0x1e})
runtime/panic.go:1198 +0x71 fp=0xc000113db0 sp=0xc000113d80
pc=0x4039871
runtime.mapaccess2_faststr(0x10, 0xc00006db00, {0x4b66bed, 0x5})
runtime/map_faststr.go:116 +0x3d4 fp=0xc000113e18
sp=0xc000113db0 pc=0x4016d54
github.com/minio/pkg/console.glob..func17({0x4b66bed, 0x5}, {0x49f7dc0,
0xc00052a2c0})
github.com/minio/pkg@v1.0.10/console/console.go:129 +0xad
fp=0xc000113e78 sp=0xc000113e18 pc=0x412566d
github.com/minio/mc/cmd.greenText({0xc0002091b8, 0x11})
github.com/minio/mc/cmd/admin-subnet-health.go:162 +0x8b
fp=0xc000113eb0 sp=0xc000113e78 pc=0x489818b
github.com/minio/mc/cmd.fetchServerHealthInfo.func1.1({0x4b6fe33, 0xd},
{0x4cc7fe8, 0x1}, 0x0) …
```
> console: Protect access to theme map

- iam/policy/admin-action.go
This policy is not required as the concept of subnet license is going
to be replaced by cluster level api keys.
This reverts commit e71c4f6ea8372a1612da0f7887f513ead2f5f301.
> Revert "Add policy for getting subnet license (#13)"

- randreader/randreader.go
- randreader/rangreader_test.go
- randreader/xor.go
- randreader/xor_amd64.go
- randreader/xor_amd64.s
- randreader/xor_noasm.go
Provides infinite stream of pseudorandom data.
```
math/rand:
BenchmarkMathRand-32               20776             58177 ns/op        1718.88 MB/s           0 B/op          0 allocs/op
This:
BenchmarkReader-32                385144              2967 ns/op        33702.78 MB/s          0 B/op          0 allocs/op
This, no asm:
BenchmarkReader-32                197226              5938 ns/op        16839.56 MB/s          0 B/op          0 allocs/op
```
I have tested the output is incompressible and that asm and no-asm produces the same output.
> Add pseudo-random reader

- env/web_env.go
On certain environments, 3 second timeout is too small causing MinIO to panic and fail complaining the environment could't be resolved
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>
> Increase lookupEnv timeout to 6.5 seconds

- bucket/policy/action.go
- bucket/policy/condition/key_test.go
- bucket/policy/condition/keyname.go
Code update of pkg minio to use running ExistingObjectTag in 'Get Object Action' as define in S3 iam policy declaration.
The code is also ready to be push on the minio/minio code when theses modications are accepted (if it was :) )
> implement usage of ExistingObjectTag in GetObjectAction

- iam/policy/admin-action.go
Needed for `mc admin bucket import|export alias/bucket`
> iam/policy: Add import/export metadata admin actions

- certs/certs.go
- certs/manager.go
This commit adds a new `Certificate` type
that supports reloading:
- after a time period
- changes to the certificate / private key file
- OS signals
This type will be used by MinIO to implement
reloading a certificate - e.g. for KES, or some WebHook.
> certs: add reloadable `Certificate` type

- iam/policy/actionset.go
- iam/policy/kms-action.go
- iam/policy/statement.go
Adds IAM policies to control access to minio handlers that will communicate with KES.
The handlers will be added in minio in another PR in which i'm currently working on.
Please let me know if there are more places where i need to make changes since this is the first time i work with policies.
Closes: https://github.com/miniohq/engineering/issues/924
> Add IAM policies  to control access to KES APIs

- iam/policy/admin-action.go
This is needed to avoid using S3 request validation in the admin handler ReplicationDiff() in MinIO server side
> Add admin:ReplicateDiff permission

- ldap/ldap.go
- ldap/validation.go
- ldap/validation_test.go
Adds `SRVRecordName` configuration parameter and validation for it. The
value can be `ldaps`, `ldap` or the special value `on`. This value is
combined with the `ServerAddr` parameter to lookup a DNS SRV record for
finding target LDAP servers.
The SRV record name format is always `_service._proto.domainname`. For LDAP
`proto` value here is always `tcp`. The `service` value is usually
`ldap`, and sometimes `ldaps`. When `SRVRecordName` is set to `ldap` or
`ldaps`, this value is substituted for `service`. The `domainname` value
is given by the `ServerAddr` parameter.
When a different SRV record name needs to be given, set `SRVRecordName`
to the special value `on`, and set the `ServerAddr` to the full SRV
record name, e.g. `_ldapish._tcpish.myldapserver.com`.
> Add LDAP SRV Record lookup support

- logger/message/audit/entry.go
- logger/message/log/entry.go
Since we have a need to unmarshal the Audit log structure we are moving it to `pkg`
Signed-off-by: Daniel Valdivia <18384552+dvaldivia@users.noreply.github.com>
> Move Audit and Log structures from minio/internal/logger

- logger/message/audit/entry.go
- Request path and Host are interesting information for troubleshooting
- Type to specify what type of audit messages is this, it can be S3 operations, admin management, bucket management. It would be easier with this to filter audit logs
> Add request path and Host and type to the audit

- bucket/policy/policy.go
- bucket/policy/policy_test.go
- iam/policy/policy.go
- iam/policy/policy_test.go
It is faster to merge multiple in a single pass than to merge policies pairwise. Also adds a test for MergePolicies.
> Replace Policy.Merge() with MergePolicies()

- bucket/policy/resource.go
- bucket/policy/resource_test.go
- wildcard/match.go
- wildcard/match_test.go
This fixes some corner cases in bucket matching in bucket policy
resources.
Failing tests for bucket/policy resource in existing implementation are
added.
This happens because we cannot parse out a unique bucket pattern from a
resource string in all cases: when resource pattern is
`mybucket*a/myobject*`, it should match `mybucket/a/myobject`.
For this pattern, the buckets matched are:
1. `mybucket` (e.g. resource value is "mybucket/a/myobject"),
2. `mybucketXa`, where X is a string not containing a `/` (e.g.
resource value is "mybucket-east-a/myobject"), and
3. `mybucketY`, where Y is a string not containing a `/` (e.g.
resource value that matches is "mybucket22/a/myobject")
To fix this a new MatchAsPatternPrefix function added to wildcard
package and bucket name matching code is updated.
> fix: bucket matching for bucket policy resource

- policy/condition/ipaddrfunc.go
[reference](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_condition_operators.html#Conditions_IPAddress)
> If you specify an IP address without the associated routing prefix, IAM uses the default prefix value of /32.
> Fix bare IP addresses

- sftp/sftp.go
This composable SFTP implementation was made in preparation for extracting the current SFTP implementation details out of [minio](github.com/minio/minio) so they can be used elsewhere.
I did not add any code that changes the basic functionality of the current SFTP boilerplate code within [minio](github.com/minio/minio). We can improve on that later if needed.
The implementation is in-line with the current FTP package we are using which makes the composition of the FTP and SFTP packages feel familiar.
At first I was thinking about refactoring this into `github.com/minio/internal` but it felt strange to be imporint `github.com/minio` into the minwall which is where we would also be using this pkg. The second option was to create a new repository for this wrapper, but that also felt like it …
> basic composable sftp server boilerplate

- subnet/license.go
This package will help with license validation for MinIO tools.
Sample usage:
```golang
lv, err := subnet.NewLicenseValidator(subnet.LicenseValidatorParams{
TLSClientConfig:   getTLSConfig(globalConfig.Minio.TLS),
LicenseFilePath:   cliCtx.String("license"),
DevMode:           cliCtx.IsSet("dev") || cliCtx.GlobalIsSet("dev"),
ExpiryGracePeriod: 60 * 24 * time.Hour, // 60 days
})
if err != nil {
console.Fatalf("error creating license validator: %s\n", err)
}
li, err := lv.ValidateEnterpriseLicense()
if err != nil {
console.Fatalf("license validation failed: %s\n", err)
}
if li.ExpiresAt.Before(time.Now()) {
// license is expired, but is within grace period
console.Errorf("license has expired on %v, renew immediately to avoid outage.\n", li.ExpiresAt)
}
```
This internally uses the …
> Add subnet package for license validation

- policy/action.go
- policy/action_test.go
- policy/actionset.go
- policy/actionset_test.go
- policy/bucket-policy-statement.go
- policy/bucket-policy-statement_test.go
- policy/bucket-policy.go
- policy/policy.go
- policy/policy_test.go
- policy/s3-action.go
- policy/statement.go
- policy/statement_test.go
- workers/workers_test.go
- Add ActionType and improve validation.
- Remove useless {policy,statement}.isValid
- Rename BucketPolicy`.isValid` to `.validate`
- Fix one-off typed constant AbortMultipartUploadAction to be untyped.
Mainly code improvement. Add a validation for Action and NotAction given in same statement.
> Introduce S3Action type for S3 actions

- licverifier/verifier.go
- subnet/license.go
There are going to be multiple variants of ENTERPRISE license. So add ability to pass a list of accepted plans to the validation function.
Also read the optional new field `trial` from the license and use it in the validation (trial licenses don't get grace period after expiry)
> Take accepted plans as input to validateEnterpriseLicense

- subnet/license.go
- Allow license validation without future expiry notification
There could be certain flows where the caller doesn't want to be notified when the license expires. In such cases, the caller can pass the expiry channel as nil, and in that case, the goroutine to schedule future license validations should not be spawned.
- Allow passing license token for validation
In some cases e.g. enterprise-console, caller may want to explicitly pass the license token for validation. Accept it in the param LicenseToken and when passed, do not try to read the token from env variable or minio.license file.
> Improvements in enterprise license validator

- ldap/ldap.go
- ldap/validation.go
Also stores the the base DN returned by the LDAP server as a normalized value in the configuration struct. This is used for other validations in the server code.
> fix: Validate base DN existence with LDAP server

- .github/workflows/go.yml
- .github/workflows/ldap.yaml
- Makefile
- certs/certs_test.go
- certs/manager.go
- go.mod
- ldap/ldap.go
- ldap/validation.go
- ldap/validation_test.go
- policy/action.go
- policy/admin-action.go
- policy/bucket-policy-statement.go
- policy/bucket-policy-statement_test.go
- policy/bucket-policy_test.go
- policy/condition/stringfunc.go
- policy/constants.go
- policy/policy_test.go
- policy/principal.go
- policy/resource.go
- policy/statement.go
- policy/statement_test.go
- policy/sts-action.go
- quick/quick.go
- subnet/license.go
- With this change, if additional LDAP attributes are specified in the
configuration, the server will fetch them when a user's DN is looked up
via `LookupUsername` (renamed here from `LookupDN`) and `LookupUserDN`.
The return types of these APIs are changed.
- Bump up to v3 as this causes API breakage.
- Update CI actions versions
> Update LDAP API to lookup addl. attributes

- .github/workflows/vulncheck.yml
- subnet/license.go
Currently if the license token is read from the license file, the variable LicenseToken on the verifier remains empty, and caller cannot get the token value without reading the file again.
Keeping the read token in LicenseToken variable will help the caller to use it if required e.g. to automatically set the subnet license config if not present.
> Keep license token read from file

- subnet/license.go
When license token is read from the license file, it can contain a newline at the end. If we try to set the same license in subnet config along with api_key, it fails with error:
`unknown sub-system  api_key`
as the api_key part moves to next line. Removing whitespace from the license token fixes this.
> Trim license token

- certs/certs_test.go
- certs/manager.go
The default Go TLS implementation always returns the first certificate (that's the "default" or "fallback" certificate) if none of the certificates match ([source](https://cs.opensource.google/go/go/+/refs/tags/go1.22.5:src/crypto/tls/common.go;l=1162)). Although that may be an issue for the client, the TLS handshake can continue. If no certificate is returned at all, the TLS handshake is aborted and the client gets a TLS failure.
MinIO always returns the default certificate if there is only one certificate (source) or when no server-name is set. If multiple certificates are added and none of them matches then `nil` is returned. Although the function returns an error, this error isn't visible in the console and/or `mc admin trace`.
This PR changes the behavior, so it always returns the …
> Use default certificate if no certificates match

- ellipses/ellipses_test.go
- ellipses/list_test.go
- wildcard/match.go
- wildcard/match_test.go
Also avoid very expensive string -> slice conversion
```
λ benchcmp before.txt after.txt
benchmark                                      old ns/op     new ns/op     delta
BenchmarkMatchSimple/0-prefix-reference-32     0.23          0.23          -0.55%
BenchmarkMatchSimple/bench-0-32                3771          3.83          -99.90%
BenchmarkMatchSimple/bench-1-32                0.93          0.72          -22.71%
BenchmarkMatchSimple/bench-2-32                0.70          0.59          -15.65%
BenchmarkMatchSimple/bench-3-32                1.63          1.41          -13.58%
BenchmarkMatchSimple/bench-4-32                201           6.24          -96.89%
BenchmarkMatchSimple/bench-5-32                77.6          18.2          -76.49%
BenchmarkMatchSimple/bench-6-32 …
```
> Fix deep recursion on star end

- policy/admin-action.go
This will be checked subsequently in minio for a new admin api 'license-info' that returns information about the license. That api will finally be used by clients to fetch and display the license details.
> Add new action for getting license info

- net/tcp.go
- net/tcp_linux.go
- net/tcp_other.go
This commit adds the `TCPConfig` structure from minio/minio and exposes it as part of the `net` package.
> net: add `TCPConfig` structure from minio/minio

- net/tcp_linux.go
This commit prevents a panic if a `net.Dialer.Control` function is a pointer to the `TCPConfig.Control` method where `TCPConfig` is nil.
For example:
```
var conf *xnet.TCPConfig
dialer := net.Dialer{
Control: conf.Control,
}
```
> net: avoid TCPConfig nil pointer deref

- policy/statement.go
- policy/statement_test.go
Resolves https://github.com/minio/minio/issues/20449
I also added some tests.
By the way, some existing tests seem to be duplicate of each other, can somebody understand what their use is? If not, I may remove them.
Because:
- `anonGetBucketLocationArgs` and `getBucketLocationArgs` are exactly the same
- `anonPutObjectActionArgs` and `putObjectActionArgs` are exactly the same
- `anonGetObjectActionArgs` and `gutObjectActionArgs` are exactly the same
> Fix statement.IsAllowed when bucket disallowed

- subnet/license.go
The MinIO console attempts to verify the license key. It needs the public key to verify the license signature and it downloads the key from subnet. MinIO is not supposed to contact external sites, unless explicitly asked to do so (https://github.com/minio/console/issues/3456).
It now always uses the embedded public key (like it already did when subnet couldn't be reached). All license based products will be moving to AIStor eventually, so having the ability to deal with a rotating public key is less important.
> Always use offline public key for license verification

- net/tcp.go
This commit skips the TCP connection config if `TCPConfig` is nil. A nil config should indiciate no connection customization.
> net: do not configure TCP connections without a config

- policy/bucket-policy-statement.go
- policy/bucket-policy-statement_test.go
- policy/bucket-policy_test.go
- policy/policy_test.go
- policy/statement.go
- policy/statement_test.go
Adds NotResource policy element as specified in S3 docs. https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements_notresource.html
Same reason as #142, but that one only added NotResource for bucket policies. This adds NotResource for regular policies and fixes a problem with how NotResource was interpreted for bucket policies.
Also makes Action and NotAction mutually exclusive in a single statement to align with AWS documentation
https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_elements.html
> Add NotResource policy statement element and fix NotResource for bucket policies

- .golangci.yml
- certs/ca-certs.go
- certs/ca-certs_test.go
- certs/cert_pool_nix.go
- ellipses/ellipses_test.go
- ellipses/list_test.go
- env/web_env.go
- mimedb/util/gen-db.go
- net/port.go
- policy/condition/stringfunc.go
- quick/encoding.go
- quick/quick.go
- quick/quick_test.go
- safe/safe.go
- safe/safe_test.go
- sys/threads.go
- xtime/time_contrib.go
This PR upgrades the Golang CI linter to v2. It also introduced some new rules, so also fixed the new linter issues (or surpressed them in the configuration).
> Use golangci-lint v2

- net/port.go
Context: https://github.com/miniohq/eos/issues/646 - This change introduces a reusable function for use in https://github.com/miniohq/eos/pull/649.
> chore: Get Next Immediate Port

- policy/admin-action.go
Trying to add a policy with admin:InspectData returns error
> Add missing inspect data action

- certs/manager.go
The current `certs.Manager` only allows reloading of existing certificates. These certificates are reloaded when the certificate file (on disk) is changed or when the manager receives `SIGHUP`.
For AIStor operator, we should also support adding new certificates. The sidecar will copy the certificates to the appropriate location and instruct MinIO to reload **ALL** certificates by sending `SIGHUP`. By disabling the auto-reload functionality in `certs.Manager`, reloading the certificates twice (and possible dangling Go-routines) will be prevented.
If `certs.WithDisableAutoReload()` is not added, then functionality is still the same.
This is required for https://github.com/miniohq/eos/pull/554.
> Allow disabling auto-reload

- policy/admin-action.go
Adding NodeList, NodeInfo and DriveList
DriveList is currently not in use inside minio, but will be implemented with the new v4 apis
> adding admin:NodeList, NodeInfo and DriveList

- policy/policy.go
To allow for optimizations at higher level
> Add hasDeny field to Policy

- go.mod
- go.sum
- oidc/utils.go
related to: https://github.com/miniohq/eos/pull/1085
move common oidc tests utils to minio/pkg
moving them here so that we can use it in both eos & eos itegration tests sources as common dependency.
> move common oidc tests utils to minio/pkg

- policy/constants.go
closes issue: https://github.com/miniohq/aistor-console/issues/4107
due to not explictly denying create user action, readonly LDAP user in aistor can access "Add User" button. 
since the https://github.com/minio/pkg/blob/2567be34479e09579aab5f5b47d1aa9875d9f168/policy/policy.go#L159
policy go used on aistor console session controller it's giving create user action permission to readonly LDAP user.
> fix: readonly LDAP user can access "Add User" button
